name: Terraform CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/terraform-ci.yaml"

env:
  AWS_REGION: ap-southeast-1

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.47.0

      - name: Setup Checkov
        run: |
          pip install checkov

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Run TFLint
        id: tflint
        run: tflint --recursive --format compact

      - name: Run Checkov
        id: checkov
        run: checkov -d . --quiet

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
